### ISSUE TITLE
eror install ?

### ISSUE THREAD

**Issue by saeedkh11** [innot/AdvPiStepper#1]
hi. i try this code for install :  pip install advpistepper. eror :Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/advpistepper/
how install packages?

**Comment by innot** [comment]
Hi,

at this time AdvPiStepper has not yet been uploaded to the regular PyPI.

But it has been uploaded to the test.pypi incubator. To install it from there try the following:

py -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple advpistepper

Please be advised that AdvPiStepper has not been officially released yet and is not feature complete. User discretion is advised.


Cheers,

Thomas
